### ISSUE TITLE
SEVERE: error in HTTP handler

### ISSUE THREAD

**Issue by pmdoll** [dollabs/planviz#25]
Planviz producess the exception below when browser is terminated / Quit .

`xxx-yyy ~/p/p/jahmm-example> planviz 
PLANVIZ server ready
Oct 05, 2016 4:19:00 PM aleph.http.server invoke
SEVERE: error in HTTP handler
java.lang.IllegalArgumentException: No implementation of method: :render of protocol: #'compojure.response/Renderable found for class: java.lang.Boolean
    at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568)
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560)
    at compojure.response$fn__189$G__184__196.invoke(response.clj:6)
    at compojure.response$fn__220.invokeStatic(response.clj:37)
    at compojure.response$fn__220.invoke(response.clj:21)
    at compojure.response$fn__189$G__184__196.invoke(response.clj:6)
    at compojure.response$fn__216.invokeStatic(response.clj:33)
    at compojure.response$fn__216.invoke(response.clj:21)
    at compojure.response$fn__189$G__184__196.invoke(response.clj:6)
    at compojure.core$make_route$fn__1533.invoke(core.clj:135)
    at compojure.core$wrap_route_middleware$fn__1526.invoke(core.clj:122)
    at compojure.core$wrap_route_info$fn__1530.invoke(core.clj:126)
    at compojure.core$if_route$fn__1502.invoke(core.clj:45)
    at compojure.core$if_method$fn__1492.invoke(core.clj:27)
    at compojure.core$routing$fn__1540.invoke(core.clj:151)
    at clojure.core$some.invokeStatic(core.clj:2592)
    at clojure.core$some.invoke(core.clj:2583)
    at compojure.core$routing.invokeStatic(core.clj:151)
    at compojure.core$routing.doInvoke(core.clj:148)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$apply.invoke(core.clj:641)
    at compojure.core$routes$fn__1544.invoke(core.clj:156)
    at planviz.server$log_request_handler$fn__17759.invoke(server.clj:600)
    at ring.middleware.flash$wrap_flash$fn__1645.invoke(flash.clj:35)
    at ring.middleware.session$wrap_session$fn__2603.invoke(session.clj:103)
    at ring.middleware.keyword_params$wrap_keyword_params$fn__2631.invoke(keyword_params.clj:35)
    at ring.middleware.nested_params$wrap_nested_params$fn__2675.invoke(nested_params.clj:86)
    at ring.middleware.multipart_params$wrap_multipart_params$fn__2795.invoke(multipart_params.clj:133)
    at ring.middleware.params$wrap_params$fn__2815.invoke(params.clj:64)
    at ring.middleware.cookies$wrap_cookies$fn__2508.invoke(cookies.clj:161)
    at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__2921.invoke(absolute_redirects.clj:38)
    at ring.middleware.resource$wrap_resource$fn__2839.invoke(resource.clj:28)
    at ring.middleware.content_type$wrap_content_type$fn__2890.invoke(content_type.clj:30)
    at ring.middleware.default_charset$wrap_default_charset$fn__2904.invoke(default_charset.clj:26)
    at ring.middleware.not_modified$wrap_not_modified$fn__2877.invoke(not_modified.clj:52)
    at ring.middleware.gzip$wrap_gzip$fn__2993.invoke(gzip.clj:65)
    at aleph.http.server$handle_request$fn__15732$f__11652__auto____15733.invoke(server.clj:156)
    at clojure.lang.AFn.run(AFn.java:22)
    at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
    at manifold.executor$thread_factory$reify__11544$f__11545.invoke(executor.clj:44)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.lang.Thread.run(Thread.java:744)
`

**Comment by pmdoll** [comment]
This issue seems to have creeped  in the most recent commits as previously built planviz does not exhibit this error.
